# Generated by Django 4.2.15 on 2024-12-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
