# Generated by Django 4.2.15 on 2024-12-05 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_cover_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover_image_url',
            new_name='cover_image',
        ),
    ]
